[rospy.client][INFO] 2012-12-15 20:00:00,206: init_node, name[/depth_detection], pid[9702]
[xmlrpc][INFO] 2012-12-15 20:00:00,206: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-15 20:00:00,206: Started XML-RPC server [http://pc:54879/]
[rospy.init][INFO] 2012-12-15 20:00:00,207: ROS Slave URI: [http://pc:54879/]
[rospy.impl.masterslave][INFO] 2012-12-15 20:00:00,207: _ready: http://pc:54879/
[xmlrpc][INFO] 2012-12-15 20:00:00,207: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-15 20:00:00,208: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-15 20:00:00,307: registered with master
[rospy.rosout][INFO] 2012-12-15 20:00:00,352: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-15 20:00:00,354: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-15 20:00:00,356: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.core][INFO] 2012-12-15 20:00:12,011: signal_shutdown [debug]
[rospy.impl.masterslave][INFO] 2012-12-15 20:00:12,017: debug
[rospy.topics][WARNING] 2012-12-15 20:00:12,152: during shutdown, bad callback: <bound method DepthDetector.depth_cb of <__main__.DepthDetector instance at 0x38e19e0>>
Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/topics.py", line 581, in _invoke_callback
    cb(msg)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 296, in depth_cb
    (contours, img_contours) = self.get_contours(img_fore)
  File "/home/alex/MAS/CV/project/cv_nxtdrive/src/depth_detection.py", line 119, in get_contours
    brect = cv2.boundingRect(c)
error: /tmp/buildd/libopencv-2.3.1+svn6514+branch23/modules/imgproc/src/contours.cpp:1664: error: (-215) points.checkVector(2) >= 0 && (points.depth() == CV_32F || points.depth() == CV_32S) in function boundingRect


[rospy.core][INFO] 2012-12-15 20:00:12,422: signal_shutdown [atexit]
