[rospy.client][INFO] 2012-12-14 20:25:15,547: init_node, name[/depth_detection], pid[21237]
[xmlrpc][INFO] 2012-12-14 20:25:15,547: XML-RPC server binding to 0.0.0.0
[xmlrpc][INFO] 2012-12-14 20:25:15,548: Started XML-RPC server [http://pc:59546/]
[rospy.init][INFO] 2012-12-14 20:25:15,548: ROS Slave URI: [http://pc:59546/]
[rospy.impl.masterslave][INFO] 2012-12-14 20:25:15,548: _ready: http://pc:59546/
[xmlrpc][INFO] 2012-12-14 20:25:15,549: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-14 20:25:15,549: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-14 20:25:15,649: registered with master
[rospy.rosout][INFO] 2012-12-14 20:25:15,688: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-14 20:25:15,691: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-14 20:25:15,692: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.core][INFO] 2012-12-14 20:25:29,130: signal_shutdown [signal-2]
[rospy.impl.masterslave][INFO] 2012-12-14 20:25:29,169: signal-2
[rospy.internal][ERROR] 2012-12-14 20:25:29,208: Traceback (most recent call last):
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/impl/tcpros_base.py", line 636, in receive_once
    recv_buff(sock, b, p.buff_size)
  File "/opt/ros/electric/stacks/ros_comm/clients/rospy/src/rospy/impl/tcpros_base.py", line 107, in recv_buff
    d = sock.recv(buff_size)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[rospy.core][INFO] 2012-12-14 20:25:29,270: signal_shutdown [atexit]
